name: Deploy Pygame to Web
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pygbag
        run: pip install pygbag

      - name: Build Web Version
        # Ye command index.html aur web files generate karega
        run: python3 -m pygbag --build --no_terminal .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web' # Pygbag files yahan banti hain

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
